languageCode = "en-us"
defaultContentLanguage = "en"
author = "Joao Osorio"
title = "Ozzie.eu"
theme = "terminal"
paginate = 5
enableRobotsTXT = true

# Required for Chroma and the custom syntax highlighting.
[markup.highlight]
  noClasses = false

googleAnalytics = ""

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[params]
  contentTypeName = "post"
  showMenuItems = 5
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true
  autoCover = true
  showLastUpdated = false

[languages]
  [languages.en]
    languageName = "English"
    title = "Ozzie.eu"

    [languages.en.params]
      subtitle = "Love to code although it bugs me."
      owner = "Joao Osorio"
      keywords = "joao,osorio,ozzie,blog"
      copyright = "© Copyright Joao Osorio"
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"

      [languages.en.params.logo]
        logoText = "Ozzie.eu"
        logoHomeLink = "/"

    [languages.en.menu]
        [[languages.en.menu.main]]
          name = "Home"
          url = "/"
          weight = 1
        [[languages.en.menu.main]]
          name = "All Posts"
          url = "/post"
          weight = 2
        [[languages.en.menu.main]]
          name = "About"
          url = "/about"
          weight = 3
        [[languages.en.menu.main]]
          name = "Tags"
          url = "/tags"
          weight = 4
        [[languages.en.menu.main]]
          name = "Categories"
          url = "/categories"
          weight = 5
